# Homebrew cask for Noats.
#
# Generated by the Noats release pipeline: every release rewrites `version`
# and `sha256` against the published, notarized DMG. Do not hand-edit them.
cask "noats" do
  version "0.1.12"
  sha256 "e774878bd036a86e9aec2498a10e5ac34a59ff0772c8cb237af9671574eacb5b"

  # Versioned artifact from the same R2 bucket the in-app updater polls, so a
  # brew install and an auto-update always agree on what 0.1.3 is.
  url "https://updates.noats.ai/releases/stable/darwin/arm64/Noats-#{version}-arm64.dmg"
  name "Noats"
  desc "Local-first meeting notes with on-device transcription and dictation"
  homepage "https://noats.ai/"

  # electron-updater's own feed manifest, which is exactly what the
  # :electron_builder strategy parses.
  livecheck do
    url "https://updates.noats.ai/releases/stable/darwin/arm64/latest-mac.yml"
    strategy :electron_builder
  end

  # The app ships a working Squirrel/electron-updater path, so Homebrew should
  # not fight it over version bumps.
  auto_updates true
  # arm64 only, and LSMinimumSystemVersion is 14.2 (forge.config.ts extendInfo).
  # Cask macOS requirements are whole releases and a bare symbol means "this
  # release or newer", so :sonoma is the closest expressible floor; 14.0/14.1
  # users get a launch-time refusal instead.
  depends_on arch: :arm64
  depends_on macos: :sonoma

  app "Noats.app"

  # Uninstall leftovers. Speech models stored in Noats' own folder live
  # inside Application Support/Noats (SpeechModels/), so the first entry
  # removes them. The shared FluidAudio cache at ~/Library/Application
  # Support/FluidAudio is deliberately NOT listed, permanently: it belongs
  # to every FluidAudio-based app on the machine, and Noats uses models
  # found there in place without ever moving or deleting them.
  zap trash: [
    "~/Library/Application Support/Noats",
    "~/Library/Caches/ai.noats.app",
    "~/Library/HTTPStorages/ai.noats.app",
    # Pre-0.1.0 electron-log default; the live log moved under Application
    # Support so a scratch profile could not pollute it.
    "~/Library/Logs/Noats",
    "~/Library/Preferences/ai.noats.app.plist",
    "~/Library/Saved Application State/ai.noats.app.savedState",
  ]
end
